name: Auto PR for feature branches

on:
  push:
    branches:
      - 'feature/**'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          base: develop
          branch: ${{ github.ref_name }}
          title: "Auto PR: ${{ github.ref_name }} → develop"
          body: "PR criado automaticamente de ${{ github.ref_name }} para develop."
